spring.application.name=reportify

# Lokale und dauerhaft gespeicherte H2-Datenbank
spring.datasource.url=jdbc:h2:file:./data/reportify
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Datenbanktabellen anhand unserer Java-Entities aktualisieren
spring.jpa.hibernate.ddl-auto=update

# Datenbankzugriffe sollen innerhalb der Services abgeschlossen werden
spring.jpa.open-in-view=false